### ISSUE TITLE
(Question) What do you mean with legal way?

### ISSUE THREAD

**Issue by TimWitzdam** [ippen/studydrive_downloader#1]
Hey, what if I theoretically found a way to still download documents but which forces me to be logged into StudyDrive.
I'm guessing you could imagine what I mean.

What would make this way more illegal than your "old" way of downloading the PDFs?

**Comment by ippen** [comment]
Well I'm not a lawyer. But I just fetched data which was just lying in their database and could easily be accessed with a post request.
If you found another way where it is necessary to be logged in, go ahead and implement it. Should not be an issue, this is how many web scrapers work too.
Feel free to fork my repo, implement it, do a  pull request and if it works I will give you big credits to the website as well and make it live again :)

Unfortunately I do not have enough time myself to implement it.

**Comment by Curve** [comment]
I've put up an alternative here: https://www.studydrive.lol/

**Comment by sposaceee** [comment]
> I've put up an alternative here: https://www.studydrive.lol/

Doesn't work for me. Just empty PDF.

**Comment by Curve** [comment]
> > I've put up an alternative here: https://www.studydrive.lol/
> 
> Doesn't work for me. Just empty PDF.

Which PDF are you trying to download? I'll take a look ^^

**Comment by sposaceee** [comment]
> > > I've put up an alternative here: https://www.studydrive.lol/
> > 
> > 
> > Doesn't work for me. Just empty PDF.
> 
> Which PDF are you trying to download? I'll take a look ^^

https://www.studydrive.net/de/doc/introprog-klausurspicker/593764

the cheat sheet would be nice for my upcoming test. :)
actually it works for https://www.studydrive.net/de/doc/zusammenfassung-introprog/1282116 :)

i think there is a diffrence between them because the first one is a png and the second one a pdf.

**Comment by Curve** [comment]
> > > > I've put up an alternative here: https://www.studydrive.lol/
> > > 
> > > 
> > > Doesn't work for me. Just empty PDF.
> > 
> > 
> > Which PDF are you trying to download? I'll take a look ^^
> 
> https://www.studydrive.net/de/doc/introprog-klausurspicker/593764
> 
> the cheat sheet would be nice for my upcoming test. :) actually it works for https://www.studydrive.net/de/doc/zusammenfassung-introprog/1282116 :)
> 
> i think there is a diffrence between them because the first one is a png and the second one a pdf. my bad

Issue is fixed - was not the file type but my re-use logic :sweat_smile:

**Comment by sposaceee** [comment]
> > > > > I've put up an alternative here: https://www.studydrive.lol/
> > > > 
> > > > 
> > > > Doesn't work for me. Just empty PDF.
> > > 
> > > 
> > > Which PDF are you trying to download? I'll take a look ^^
> > 
> > 
> > https://www.studydrive.net/de/doc/introprog-klausurspicker/593764
> > the cheat sheet would be nice for my upcoming test. :) actually it works for https://www.studydrive.net/de/doc/zusammenfassung-introprog/1282116 :)
> > i think there is a diffrence between them because the first one is a png and the second one a pdf. my bad
> 
> Issue is fixed - was not the file type but my re-use logic 😅

works like a charm. thank you!

**Comment by Curve** [comment]
> > > > > > I've put up an alternative here: https://www.studydrive.lol/
> > > > > 
> > > > > 
> > > > > Doesn't work for me. Just empty PDF.
> > > > 
> > > > 
> > > > Which PDF are you trying to download? I'll take a look ^^
> > > 
> > > 
> > > https://www.studydrive.net/de/doc/introprog-klausurspicker/593764
> > > the cheat sheet would be nice for my upcoming test. :) actually it works for https://www.studydrive.net/de/doc/zusammenfassung-introprog/1282116 :)
> > > i think there is a diffrence between them because the first one is a png and the second one a pdf. my bad
> > 
> > 
> > Issue is fixed - was not the file type but my re-use logic 😅
> 
> works like a charm. thank you!

no problem - thanks for reporting!

**Comment by ippen** [comment]
@Curve  Thank you for your work :) The website is now live again with credits to your work :)
