### ISSUE TITLE
{"error":{"code":404,"message":"FILE_NOT_FOUND","errors":[]}} after "download pdf"

### ISSUE THREAD

**Issue by Meatballonbread** [ippen/studydrive_downloader#2]
Danke für das Bereitstellen. Jedoch erhalte ich diese Fehlermeldung, hast du eine Idee?

**Comment by Hendrik7889** [comment]
same here

**Comment by ippen** [comment]
As it is written in the Readme here:
[Notice](https://github.com/ippen/studydrive_downloader?tab=readme-ov-file#notice) the current method does not work anymore :/
